### ISSUE TITLE
pgspecial==1.12.0 pypi py2 package is broken

### ISSUE THREAD

**Issue by saifelse** [dbcli/pgspecial#101]
Hello!

When I run: `pip2 -v install --no-cache-dir pgspecial==1.12.0`, pgspecial fails to install indicating README.rst is missing:
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Using pip 20.3.4 from /Users/saif/.pyenv/versions/2.7.17/lib/python2.7/site-packages/pip (python 2.7)
...
1 location(s) to search for versions of pgspecial:
* https://pypi.org/simple/pgspecial/
Fetching project page and analyzing links: https://pypi.org/simple/pgspecial/
Getting page https://pypi.org/simple/pgspecial/
Found index url https://pypi.org/simple
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pgspecial/ HTTP/1.1" 200 2503
  ...
  Found link https://files.pythonhosted.org/packages/38/11/88ad5b0ac10f1510050717c266159aa6eb14bb11260d00e7b2ca788eabf8/pgspecial-1.12.0.tar.gz#sha256=a514a9e7194983e9641a927bbb6cd172b7178ecf331d56e40399a4d8149f81e2 (from https://pypi.org/simple/pgspecial/), version: 1.12.0
Given no hashes to check 1 links for project 'pgspecial': discarding no candidates
Using version 1.12.0 (newest of versions: 1.12.0)
Collecting pgspecial==1.12.0
  Created temporary directory: /private/var/folders/vp/yb1jgm2x05g3xcyn2xj564gw0000gq/T/pip-unpack-021OJl
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/38/11/88ad5b0ac10f1510050717c266159aa6eb14bb11260d00e7b2ca788eabf8/pgspecial-1.12.0.tar.gz HTTP/1.1" 200 46281
  Downloading pgspecial-1.12.0.tar.gz (46 kB)
     |████████████████████████████████| 46 kB 2.4 MB/s
  Added pgspecial==1.12.0 from https://files.pythonhosted.org/packages/38/11/88ad5b0ac10f1510050717c266159aa6eb14bb11260d00e7b2ca788eabf8/pgspecial-1.12.0.tar.gz#sha256=a514a9e7194983e9641a927bbb6cd172b7178ecf331d56e40399a4d8149f81e2 to build tracker '/private/var/folders/vp/yb1jgm2x05g3xcyn2xj564gw0000gq/T/pip-req-tracker-EQsgYU'
    Running setup.py (path:/private/var/folders/vp/yb1jgm2x05g3xcyn2xj564gw0000gq/T/pip-install-4Jf96Y/pgspecial/setup.py) egg_info for package pgspecial
    Created temporary directory: /private/var/folders/vp/yb1jgm2x05g3xcyn2xj564gw0000gq/T/pip-pip-egg-info-95aA98
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vp/yb1jgm2x05g3xcyn2xj564gw0000gq/T/pip-install-4Jf96Y/pgspecial/setup.py", line 24, in <module>
        long_description=open("README.rst").read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I've confirmed that README.rst is indeed missing from the [pypi release](https://files.pythonhosted.org/packages/38/11/88ad5b0ac10f1510050717c266159aa6eb14bb11260d00e7b2ca788eabf8/pgspecial-1.12.0.tar.gz ) while the [matching release found on GitHub](https://github.com/dbcli/pgspecial/releases/tag/v1.12.0) does contain this file.

**Comment by j-bennet** [comment]
Closed via https://github.com/dbcli/pgspecial/pull/102. Thanks a lot for reporting!

**Comment by j-bennet** [comment]
@saifelse I'd advise to avoid using python 2.x. It has reached EOL, and none of our team's CLIs support it.

**Comment by saifelse** [comment]
> @saifelse I'd advise to avoid using python 2.x. It has reached EOL, and none of our team's CLIs support it.

@j-bennet : We're still migrating some projects off of Python 2 😬, but noted! We've avoided the issue on our end by pinning pgspecial==1.11.0. Perhaps it's worth officially dropping support for Python 2?

**Comment by j-bennet** [comment]
> Perhaps it's worth officially dropping support for Python 2 for pgspecial?

Yeah, this is next item on my TODO list.
