### ISSUE TITLE
\d table, error: UnboundLocalError("local variable 'list_rule' referenced before assignment")

### ISSUE THREAD

**Issue by Maartincm** [dbcli/pgspecial#92]
While describing a table with rules, I get an error. Here is the relevant log section:

```
2019-12-12 11:24:34,150 (11974/MainThread) pgcli.main ERROR - sql: '\\d modules_executions', error: UnboundLocalError("local variable 'list_rule' referenced before assignment")
2019-12-12 11:24:34,152 (11974/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.7/dist-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/usr/local/li
b/python3.7/dist-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/usr/local/lib/python3.7/dist-packages/pgcli/pgexecute.py", line 402, in run\n    for result in pgspecial.execute(cur, sq
l):\n  File "/usr/local/lib/python3.7/dist-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/usr/local/lib/python3.7/dist-packages/pgspecial/dbcommands.py", line 717, in describe_table_detai
ls\n    results.append(describe_one_table_details(cur, nspname, relname, oid, verbose))\n  File "/usr/local/lib/python3.7/dist-packages/pgspecial/dbcommands.py", line 1274, in describe_one_table_details\nUnboundLocalError: local variable \'list_rule\' referenced before assi
gnment\n'
```

I assume the problem is around [this for loop](https://github.com/dbcli/pgspecial/blob/678afb4b9bf8c4e1323c9e9ea481b4f0536a9815/pgspecial/dbcommands.py#L1264)

Versions:
pgcli                     2.2.0                                                                                                              
pgspecial             1.11.9   

PSQL Output for the same command:
![image](https://user-images.githubusercontent.com/28577666/70721143-d8d90580-1cd3-11ea-84d4-2d2143f2f8eb.png)

**Comment by catherinedevlin** [comment]
I believe that version 3.0.0 has fixed this.  

```
create table foo (a integer, b integer);

create table if not exists fake_foo as 
  select * from foo 
  where false;

CREATE RULE "_RETURN" AS
    ON SELECT TO fake_foo 
    DO INSTEAD
        SELECT * FROM foo;

\d fake_foo                                                                                 
+----------+---------+-------------+
| Column   | Type    | Modifiers   |
|----------+---------+-------------|
| a        | integer |             |
| b        | integer |             |
+----------+---------+-------------+

```
